language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git config --global user.name "YooMo"
- git config --global user.email "1018434487@qq.com"
- cp ../README.MD README.MD
- git add -A
- git commit -m "Travis CI Auto Builder"
- git push --force -u "https://${REPO_TOKEN}@${GH_REF}" master
branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/YooMo/yoomo.github.io
  - secure: QuvciQeyLaUh8mQWqq95+0Jynzrm6rbcpiI7e8nYnv1vd/ZExkP7hfccrH2uUk0fFYxDZ2yZc1weRvJiZzrtEGqLPB2S6q89L+e1JSSTuPRNW3GYU4WdT0Bfc5V8ExikXgyqzvolKJCrih4jtYsiMSgwkGHRZZE6jYXwKrWfj8I3omC2HElNqg4d5doGmWIl+0tU8XnnBypvpRwIFWrVCCDfa1gJPkZJbMEoMYwCVN7YtbO5m2r6avk7qqPlJ6BZYqPu3rbh5Cx+qHPK207mB9sydAlEFlDYQTrT2TbZDecc2nf7BdrP3LL4kZgkORpBlNuiBDcOM7llPMNTKTMuaWJuZoPoD0gxmJYb3dI5U1aSsz6koJ6OE+37lrtZ/CKLZ2M5fMUbIdNuccSR0GAsq/Ihz5EdFPZcyPauY7DskwLtdAK39mIfEjIQX8grr8E8KlqX3IfH9whNVvnLLgRe7k43iNkxWOriSHlP2Nx/5iXaq0VhjInNjex15eOHKA3xERk7kPDPRe3trqTVvAFwLUn4KtlL7MiAha+3kpceEFUexwurtOU0Wkztb2hknEajnSW9FXEFPjoMAO0tDQCLP991yHI5B5uIUpkhWB88bkyiYZZfzLXoQecfYGK72azSG9oEyBspiyUje9VfbsrmqGFvw6MM+IoG3+trQnASMXY=
